name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  service-validation:
    runs-on: self-hosted 
    strategy:
      max-parallel: 4
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Create .env file
      env:
        HUNYUAN_SECRET_KEY: ${{ secrets.HUNYUAN_SECRET_KEY }}
        HUNYUAN_API_BASE: ${{ secrets.HUNYUAN_API_BASE }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }} 
      run: |
        echo "HUNYUAN_SECRET_KEY=$HUNYUAN_SECRET_KEY" > .env
        echo "HUNYUAN_API_BASE=$HUNYUAN_API_BASE" >> .env
        echo "MYSQL_HOST=$MYSQL_HOST" >> .env
        echo "MYSQL_PORT=$MYSQL_PORT" >> .env
        echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
        echo "MYSQL_USER=$MYSQL_USER" >> .env
        echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env


    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Run Tests with Coverage
      run: |
        coverage run manage.py test
        coverage report

